### ISSUE TITLE
TODO get teammembers onboarded to research computing

### ISSUE THREAD

**Issue by michaelchughes** [tufts-ml/time_series_prediction#4]
HPC access (looks like you need to do it yourself):
* [x] @onewland13 request HPC account
* [x] @byronperpetua request HPC account
https://it.tufts.edu/it-computing/accounts-passwords/research-cluster-account

You'll need your tufts UTLN credentials, etc.

You should request *Cluster* access, not Emboss storage

You should list me as your supervisor and request to be added to the "hugheslab" research group and storage space.

Usage box sample text:
```
I will be an active researcher in the "hugheslab" research group, developing and evaluating machine learning methods for time-series prediction problems on large datasets. I will need membership in the "hugheslab" group, access to the "hugheslab" research storage at /cluster/tufts/hugheslab/, and the ability to run jobs in parallel via the slurm scheduling system.

This request has been approved by my supervisor, Prof. Michael Hughes, Assistant Professor of Computer Science, School of Engineering
michael.hughes@tufts.edu
6176270548
UTLN: mhughe02
```

Data:
* [ ] Mike move David Kale data from odyssey to Tufts hugheslab
